# /etc/netscope/ascii_art.py

ascii_art_dict = {
    "Debian": [
        "                              _,met$$$$$gg.                ",
        "                          ,g$$$$$$$$$$$$$$$P.              ",
        "                        ,g$$P\"        \"\"\"Y$$.\".            ",
        "                       ,$$P'               `$$$.           ",
        "                     ',$$P       ,ggs.     `$$b:           ",
        "                     `d$$'     ,$P\"'   .    $$$            ",
        "                      $$P      d$'     ,    $$P            ",
        "                      $$:      $$.   -    ,d$$'            ",
        "                      $$;      Y$b._   _,d$P'              ",
        "                      Y$$.    `.`\"Y$$$$P\"'                ",
        "                      `$$b      \"-.__                     ",
        "                       `Y$$                                 ",
        "                        `Y$$.                               ",
        "                          `$$b.                             ",
        "                            `Y$$b.                          ",
        "                               \"\"\"                          "
    ],
    "Ubuntu": [
        "                              .-/+oossssoo+/-.               ",
        "                          `:+ssssssssssssssssss+:`           ",
        "                        -+ssssssssssssssssssyyssss+-         ",
        "                      .ossssssssssssssssssdMMMNysssso.       ",
        "                     /ssssssssssshdmmNNmmyNMMMMhssssss/      ",
        "                    +ssssssssshmydMMMMMMMNddddyssssssss+     ",
        "                   /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    ",
        "                  .ssssssssdMMMNhsssssssssshNMMMdssssssss.   ",
        "                  +sssshhhyNMMNyssssssssssssyNMMMysssssss+   ",
        "                  ossyNMMMNyMMhsssssssssssssshmmmhssssssso   ",
        "                  ossyNMMMNyMMhsssssssssssssshmmmhssssssso   ",
        "                  +sssshhhyNMMNyssssssssssssyNMMMysssssss+   ",
        "                  .ssssssssdMMMNhsssssssssshNMMMdssssssss.   ",
        "                   /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    ",
        "                    +sssssssssdmydMMMMMMMMddddyssssssss+     ",
        "                     /ssssssssssshdmNNNNmyNMMMMhssssss/      ",
        "                      .ossssssssssssssssssdMMMNysssso.       ",
        "                        -+sssssssssssssssssyyyssss+-         ",
        "                          `:+ssssssssssssssssss+:`           ",
        "                              .-/+oossssoo+/-.               "
    ],
    "Fedora": [
        "                               /:-------------:\\            ",
        "                            :-------------------::           ",
        "                          :-----------/shhOHbmp---:\\         ",
        "                        /-----------omMMMNNNMMD  ---:\\       ",
        "                       :-----------sMMMMNMNMP.    ---:       ",
        "                      :-----------:MMMdP-------    ---\\      ",
        "                     ,------------:MMMd--------    ---:      ",
        "                     :------------:MMMd-------    .---:      ",
        "                     :----    oNMMMMMMMMMNho     .----:      ",
        "                     :--     .+shhhMMMmhhy++   .------/      ",
        "                     :-    -------:MMMd--------------:       ",
        "                     :-   --------/MMMd-------------;        ",
        "                     :-    ------/hMMMy------------:         ",
        "                     :-- :dMNdhhdNMMNo------------;          ",
        "                     :---:sdNMMMMNds:------------:           ",
        "                     :------:://:-------------::             ",
        "                     :---------------------://               "
    ],
    "Arch Linux": [
        "                                   -`                  ",
        "                                  .o+`                 ",
        "                                 `ooo/                 ",
        "                                `+oooo:                ",
        "                               `+oooooo:               ",
        "                               -+oooooo+:              ",
        "                             `/:-:++oooo+:             ",
        "                            `/++++/+++++++:            ",
        "                           `/++++++++++++++:           ",
        "                          `/+++ooooooooooooo/`         ",
        "                         ./ooosssso++osssssso+`        ",
        "                        .oossssso-````/ossssss+`       ",
        "                       -osssssso.      :ssssssso.      ",
        "                      :osssssss/        osssso+++.     ",
        "                     /ossssssss/        +ssssooo/-     ",
        "                   `/ossssso+/:-        -:/+osssso+-   ",
        "                  `+sso+:-`                 `.-/+oso:  ",
        "                 `++:.                           `-/+/ ",
        "                 .`                                 `/"
    ],
    "Darwin": [
        "                                      ,xNMM.",
        "                                    .OMMMMo",
        "                                    OMMM0,",
        "                          .;loddo:' loolloddol;.",
        "                        cKMMMMMMMMMMNWMMMMMMMMMM0:",
        "                      .KMMMMMMMMMMMMMMMMMMMMMMMWd.",
        "                      XMMMMMMMMMMMMMMMMMMMMMMMX.",
        "                     ;MMMMMMMMMMMMMMMMMMMMMMMM:",
        "                     :MMMMMMMMMMMMMMMMMMMMMMMM:",
        "                     .MMMMMMMMMMMMMMMMMMMMMMMX.",
        "                      kMMMMMMMMMMMMMMMMMMMMMMMMWd.",
        "                      .XMMMMMMMMMMMMMMMMMMMMMMMMMMk",
        "                       .XMMMMMMMMMMMMMMMMMMMMMMMMK.",
        "                         kMMMMMMMMMMMMMMMMMMMMMMd",
        "                          ;KMMMMMMMWXXWMMMMMMMk.",
        "                            .cooc,.    .,coo:."
    ]
}
