# /etc/netscope/ascii_art.py

ascii_art_dict = {
    "Arch Linux": [
        "                                   -`                  ",
        "                                  .o+`                 ",
        "                                 `ooo/                 ",
        "                                `+oooo:                ",
        "                               `+oooooo:               ",
        "                               -+oooooo+:              ",
        "                             `/:-:++oooo+:             ",
        "                            `/++++/+++++++:            ",
        "                           `/++++++++++++++:           ",
        "                          `/+++ooooooooooooo/`         ",
        "                         ./ooosssso++osssssso+`        ",
        "                        .oossssso-````/ossssss+`       ",
        "                       -osssssso.      :ssssssso.      ",
        "                      :osssssss/        osssso+++.     ",
        "                     /ossssssss/        +ssssooo/-     ",
        "                   `/ossssso+/:-        -:/+osssso+-   ",
        "                  `+sso+:-`                 `.-/+oso:  ",
        "                 `++:.                           `-/+/ ",
        "                 .`                                 `/"
    ],
    "Darwin": [
        "                                      ,xNMM.",
        "                                    .OMMMMo",
        "                                    OMMM0,",
        "                          .;loddo:' loolloddol;.",
        "                        cKMMMMMMMMMMNWMMMMMMMMMM0:",
        "                      .KMMMMMMMMMMMMMMMMMMMMMMMWd.",
        "                      XMMMMMMMMMMMMMMMMMMMMMMMX.",
        "                     ;MMMMMMMMMMMMMMMMMMMMMMMM:",
        "                     :MMMMMMMMMMMMMMMMMMMMMMMM:",
        "                     .MMMMMMMMMMMMMMMMMMMMMMMX.",
        "                      kMMMMMMMMMMMMMMMMMMMMMMMMWd.",
        "                      .XMMMMMMMMMMMMMMMMMMMMMMMMMMk",
        "                       .XMMMMMMMMMMMMMMMMMMMMMMMMK.",
        "                         kMMMMMMMMMMMMMMMMMMMMMMd",
        "                          ;KMMMMMMMWXXWMMMMMMMk.",
        "                            .cooc,.    .,coo:."
    ],
    "Debian": [
        "                              _,met$$$$$gg.                ",
        "                          ,g$$$$$$$$$$$$$$$P.              ",
        "                        ,g$$P\"        \"\"\"Y$$.\".            ",
        "                       ,$$P'               `$$$.           ",
        "                     ',$$P       ,ggs.     `$$b:           ",
        "                     `d$$'     ,$P\"'   .    $$$            ",
        "                      $$P      d$'     ,    $$P            ",
        "                      $$:      $$.   -    ,d$$'            ",
        "                      $$;      Y$b._   _,d$P'              ",
        "                      Y$$.    `.`\"Y$$$$P\"'                ",
        "                      `$$b      \"-.__                     ",
        "                       `Y$$                                 ",
        "                        `Y$$.                               ",
        "                          `$$b.                             ",
        "                            `Y$$b.                          ",
        "                               \"\"\"                          "
    ],
    "Elementary": [
        "                         eeeeeeeeeeeeeeeee             ",
        "                      eeeeeeeeeeeeeeeeeeeeeee          ",
        "                    eeeee  eeeeeeeeeeee   eeeee        ",
        "                  eeee   eeeee       eee     eeee      ",
        "                 eeee   eeee          eee     eeee     ",
        "                eee    eee            eee       eee    ",
        "                eee   eee            eee        eee    ",
        "                ee    eee           eeee       eeee    ",
        "                ee    eee         eeeee      eeeeee    ",
        "                ee    eee       eeeee      eeeee ee    ",
        "                eee   eeee   eeeeee      eeeee  eee    ",
        "                eee    eeeeeeeeee     eeeeee    eee    ",
        "                 eeeeeeeeeeeeeeeeeeeeeeee    eeeee     ",
        "                  eeeeeeee eeeeeeeeeeee      eeee      ",
        "                    eeeee                 eeeee        ",
        "                      eeeeeee         eeeeeee          ",
        "                         eeeeeeeeeeeeeeeee             "
    ],
    "Fedora": [
        "                               /:-------------:\\            ",
        "                            :-------------------::           ",
        "                          :-----------/shhOHbmp---:\\         ",
        "                        /-----------omMMMNNNMMD  ---:\\       ",
        "                       :-----------sMMMMNMNMP.    ---:       ",
        "                      :-----------:MMMdP-------    ---\\      ",
        "                     ,------------:MMMd--------    ---:      ",
        "                     :------------:MMMd-------    .---:      ",
        "                     :----    oNMMMMMMMMMNho     .----:      ",
        "                     :--     .+shhhMMMmhhy++   .------/      ",
        "                     :-    -------:MMMd--------------:       ",
        "                     :-   --------/MMMd-------------;        ",
        "                     :-    ------/hMMMy------------:         ",
        "                     :-- :dMNdhhdNMMNo------------;          ",
        "                     :---:sdNMMMMNds:------------:           ",
        "                     :------:://:-------------::             ",
        "                     :---------------------://               "
    ],
    "Kali": [
        "                      ..............                                      ",
        "                      ..,;:ccc,.                                          ",
        "                    ......''';lxO.                                        ",
        "           .....''''..........,:ld;                                       ",
        "                     .';;;:::;,,.x,                                       ",
        "                ..'''.            0Xxoc:,.  ...                           ",
        "            ....                ,ONkc;,;cokOdc',.                         ",
        "           .                   OMo           ':ddo.                       ",
        "                              dMc               :OO;                      ",
        "                              0M.                 .:o.                    ",
        "                              ;Wd                                         ",
        "                               ;XO,                                       ",
        "                                 ,d0Odlc;,.                               ",
        "                                     ..',;:cdOOd::,.                      ",
        "                                              .:d;.':;.                   ",
        "                                                 'd,  .'                  ",
        "                                                   ;l   ..                ",
        "                                                    .o                    ",
        "                                                      c                   ",
        "                                                      .'                  ",
        "                                                       .                  "
    ],
    "Manjaro": [
        "                      ██████████████████  ████████    ",
        "                      ██████████████████  ████████    ",
        "                      ██████████████████  ████████    ",
        "                      ██████████████████  ████████    ",
        "                      ████████            ████████    ",
        "                      ████████  ████████  ████████    ",
        "                      ████████  ████████  ████████    ",
        "                      ████████  ████████  ████████    ",
        "                      ████████  ████████  ████████    ",
        "                      ████████  ████████  ████████    ",
        "                      ████████  ████████  ████████    ",
        "                      ████████  ████████  ████████    "
    ],
    "Mint": [
        "                              ...-:::::-...                  ",
        "                           .-MMMMMMMMMMMMMMM-.               ",
        "                       .-MMMM`..-:::::::-..`MMMM-.           ",
        "                     .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.         ",
        "                    -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-        ",
        "                  `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`     ",
        "                  :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:     ",
        "                 .MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.    ",
        "                 :MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:    ",
        "                 :MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:    ",
        "                 :MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:    ",
        "                 .MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.    ",
        "                  :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:     ",
        "                   :MMM:MMM:`                `:MMM:MMM:      ",
        "                    .MMM.MMMM:--------------:MMMM.MMM.       ",
        "                      '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'        ",
        "                        '.-MMMM``--:::::--``MMMM-.'          ",
        "                             '-MMMMMMMMMMMMM-'               ",
        "                                ``-:::::-``                  "
    ],
    "Redhat": [
        "                               .MMM..:MMMMMMM                     ",
        "                              MMMMMMMMMMMMMMMMMM                  ",
        "                              MMMMMMMMMMMMMMMMMMMM.               ",
        "                             MMMMMMMMMMMMMMMMMMMMMM               ",
        "                            ,MMMMMMMMMMMMMMMMMMMMMM:              ",
        "                            MMMMMMMMMMMMMMMMMMMMMMMM              ",
        "                      .MMMM'  MMMMMMMMMMMMMMMMMMMMMM              ",
        "                     MMMMMM    `MMMMMMMMMMMMMMMMMMMM.             ",
        "                    MMMMMMMM      MMMMMMMMMMMMMMMMMM .            ",
        "                    MMMMMMMMM.       `MMMMMMMMMMMMM' MM.          ",
        "                    MMMMMMMMMMM.                     MMMM         ",
        "                    `MMMMMMMMMMMMM.                 ,MMMMM.       ",
        "                     `MMMMMMMMMMMMMMMMM.          ,MMMMMMMM.      ",
        "                        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM      ",
        "                          MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:      ",
        "                             MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       ",
        "                                `MMMMMMMMMMMMMMMMMMMMMMMM:        ",
        "                                    ``MMMMMMMMMMMMMMMMM'          "
    ],
    "Slackware": [
        "                                       ::::::::                 ",
        "                                 :::::::::::::::::::            ",
        "                              :::::::::::::::::::::::::         ",
        "                            ::::::::cllcccccllllllll::::::      ",
        "                         :::::::::lc               dc:::::::    ",
        "                        ::::::::cl   clllccllll    oc:::::::::  ",
        "                       :::::::::o   lc::::::::co   oc:::::::::: ",
        "                      ::::::::::o    cccclc:::::clcc::::::::::: ",
        "                      :::::::::::lc        cclccclc:::::::::::: ",
        "                     ::::::::::::::lcclcc          lc:::::::::::",
        "                     ::::::::::cclcc:::::lccclc     oc::::::::::",
        "                     ::::::::::o    l::::::::::l    lc::::::::::",
        "                      :::::cll:o     clcllcccll     o:::::::::::",
        "                      :::::occ:o                  clc:::::::::::",
        "                       ::::ocl:ccslclccclclccclclc::::::::::::: ",
        "                        :::oclcccccccccccccllllllllllllll:::::  ",
        "                         ::lcc1lcccccccccccccccccccccccco::::   ",
        "                           ::::::::::::::::::::::::::::::::     ",
        "                             ::::::::::::::::::::::::::::       ",
        "                                ::::::::::::::::::::::          ",
        "                                     ::::::::::::               "
    ],
    "Ubuntu": [
        "                              .-/+oossssoo+/-.               ",
        "                          `:+ssssssssssssssssss+:`           ",
        "                        -+ssssssssssssssssssyyssss+-         ",
        "                      .ossssssssssssssssssdMMMNysssso.       ",
        "                     /ssssssssssshdmmNNmmyNMMMMhssssss/      ",
        "                    +ssssssssshmydMMMMMMMNddddyssssssss+     ",
        "                   /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    ",
        "                  .ssssssssdMMMNhsssssssssshNMMMdssssssss.   ",
        "                  +sssshhhyNMMNyssssssssssssyNMMMysssssss+   ",
        "                  ossyNMMMNyMMhsssssssssssssshmmmhssssssso   ",
        "                  ossyNMMMNyMMhsssssssssssssshmmmhssssssso   ",
        "                  +sssshhhyNMMNyssssssssssssyNMMMysssssss+   ",
        "                  .ssssssssdMMMNhsssssssssshNMMMdssssssss.   ",
        "                   /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    ",
        "                    +sssssssssdmydMMMMMMMMddddyssssssss+     ",
        "                     /ssssssssssshdmNNNNmyNMMMMhssssss/      ",
        "                      .ossssssssssssssssssdMMMNysssso.       ",
        "                        -+sssssssssssssssssyyyssss+-         ",
        "                          `:+ssssssssssssssssss+:`           ",
        "                              .-/+oossssoo+/-.               "
    ],
    "Ubuntu Budgie": [
        "                                ./oydmMMMMMMmdyo/.      ",
        "                             :smMMMMMMMMMMMhs+:++yhs:   ",
        "                          `omMMMMMMMMMMMN+`        `odo`",
        "                         /NMMMMMMMMMMMMN-            `sN/",
        "                       `hMMMMmhhmMMMMMMh               sMh`",
        "                      .mMmo-     /yMMMMm`              `MMm.",
        "                      mN/       yMMMMMMMd-              MMMm",
        "                     oN-        oMMMMMMMMMms+//+o+:    :MMMMo",
        "                     m/          +NMMMMMMMMMMMMMMMMm. :NMMMMm",
        "                     M`           .NMMMMMMMMMMMMMMMNodMMMMMMM",
        "                     M-            sMMMMMMMMMMMMMMMMMMMMMMMMM",
        "                     mm`           mMMMMMMMMMNdhhdNMMMMMMMMMm",
        "                     oMm/        .dMMMMMMMMh:      :dMMMMMMMo",
        "                      mMMNyo/:/sdMMMMMMMMM+          sMMMMMm",
        "                      .mMMMMMMMMMMMMMMMMMs           `NMMMm.",
        "                       `hMMMMMMMMMMM.oo+.            `MMMh`",
        "                         /NMMMMMMMMMo                sMN/",
        "                          `omMMMMMMMMy.            :dmo`",
        "                             :smMMMMMMMh+-`   `.:ohs:",
        "                                ./oydmMMMMMMdhyo/."
    ]
}
